/* Registry Pro clean source module. Edit this file directly; no runtime patch loader. */

/* ===== Source: residential-plot.js ===== */
(function(){
'use strict';
const $=id=>document.getElementById(id), txt=v=>String(v??'').trim(), num=v=>Number.isFinite(Number(v))?Number(v):0, html=v=>txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedRoad='',manualRate=false,lastPlotCalc=null;
function currentDraftType(){
  const visible=txt($('selectedTypeLabel')?.textContent||$('draftTypeMini')?.textContent);
  if(visible&&!/select deed type/i.test(visible))return visible;
  try{return txt(registrySelectedType)}catch(e){}
  return txt(window.registrySelectedType||document.body?.dataset?.registryType||'Residential Plot');
}
function isPlot(){return currentDraftType().toLowerCase()==='residential plot'}
function norm(v){return txt(v).toLowerCase().normalize('NFKC').replace(/\([^)]*\)/g,' ').replace(/[\s._\-–—/\\,;:]+/g,'').replace(/मुस्तहकम|अहतमाल|जदीद|पुराना/g,'')}
function tehsil(){try{return txt(currentJurisdiction().tehsil)}catch(e){return txt($('v120DraftTehsil')?.value||$('dashTehsil')?.value)}}
function village(){return txt($('village')?.value||$('villageSearch')?.value)}
function rows(){try{return CIRCLE_RATE_DATA||[]}catch(e){return []}}
function rowInTehsil(r){try{return r.tehsil?txt(r.tehsil)===tehsil():window.v14CircleRowInTehsil?window.v14CircleRowInTehsil(r,tehsil()):true}catch(e){return true}}
function major(r){return !!r&&(!!r.route||r.nonAgriFar!==null&&r.nonAgriFar!==undefined||/प्रमुख\s*मार्ग|मुख्य\s*मार्ग|major\s*road/i.test(txt(r.section)))}
function match(r){const q=norm(village()),vals=[r.name,r.alias,r.latinAlias,r.searchText].map(norm).filter(Boolean);return q&&vals.some(v=>v===q||(q.length>3&&v.includes(q))||(v.length>3&&q.includes(v)))}
function category(){return txt($('v123DistanceCategory')?.value)}
function rowRate(r,cat){return cat==='51-200'?num(r?.nonAgriFar):num(r?.nonAgri)}
function distanceHindi(cat){return cat==='0-50'?'0 से 50 मीटर':cat==='51-200'?'51 से 200 मीटर':cat==='200+'?'200 मीटर से अधिक':''}
function cleanRoadName(r){return txt(r?.route||r?.name).replace(/^\s*[A-Z]-\d+\s*[—–:-]\s*/i,'').trim()}
function candidates(){const cat=category();if(!cat||cat==='200+')return [];return rows().filter(r=>rowInTehsil(r)&&major(r)&&match(r)&&rowRate(r,cat)>0).filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i).sort((a,b)=>num(a.page)-num(b.page)||num(a.row)-num(b.row))}
function currentBase(){return num($('circleRateSelect')?.value||$('circleRate')?.value)}
function selected(){return candidates().find(r=>txt(r.id)===selectedRoad)||null}
function effective(){const cat=category(),r=selected(),manual=num($('v1211PlotManualRate')?.value);if(cat==='200+')return {rate:currentBase(),row:null,source:'>200m — selected village/base rate'};if(manualRate&&manual>0)return {rate:manual,row:r,source:'Manual override — verify official PDF'};if(r)return {rate:rowRate(r,cat),row:r,source:'Selected official main-road row'};return {rate:0,row:null,source:candidates().length>1?'Select exact applicable road':'Exact official road match not found'} }
function syncRoadNarrative(x){const field=$('mainRoadDistance'),cat=category();if(!field||!cat)return;if(x?.row){field.value=`${cleanRoadName(x.row)} मुख्य मार्ग से ${distanceHindi(cat)} की दूरी पर स्थित है।`}else if(cat==='200+'){field.value=`चयनित भूमि प्रमुख/मुख्य मार्ग से ${distanceHindi(cat)} की दूरी पर स्थित है।`}else if(!manualRate){field.value=''} }
function calcPlot(){try{window.recalculate();window.recalculateStampDuty();window.syncDraftPreview()}catch(e){console.warn('v1.20.14 plot calculation',e)}}
function ensureUi(){
  const distance=$('v123DistanceWrap');if(distance&&!$('v1211PlotRoad'))distance.insertAdjacentHTML('beforeend',`<div id="v1211PlotRoad" class="v1211-road v1211-plot-only"><label>Applicable Main Road / Official Reference</label><div class="v1211-road-control"><select id="v1211PlotRoadSelect" onchange="v1211PlotRoadChanged()"></select><button class="btn outline compact" type="button" id="v1211PlotRoadSource" onclick="v1211OpenPlotRoad()" disabled>View Source</button></div><div class="v1211-grid" style="margin-top:9px"><div><label>Distance Rate (editable)</label><input id="v1211PlotManualRate" type="number" min="0" step="1" oninput="v1211PlotManualChanged()"></div></div><div id="v1211PlotRoadStatus" class="v1211-road-status">Village और distance select करें।</div></div>`);
  const oldPrev=document.querySelector('.previous-title-holder-row');if(oldPrev&&!$('v1211PlotPrevious'))oldPrev.insertAdjacentHTML('afterend',card('v1211PlotPrevious','Previous Buyer / Title Holder Reference',`<div class="v1211-grid"><div><label>Name</label><input id="v1211PrevName"></div><div><label>Address</label><input id="v1211PrevAddress"></div><div><label>Regn No.</label><input id="v1211PrevRegNo"></div><div><label>Date</label><input id="v1211PrevDate" type="date"></div><div><label>Jild No.</label><input id="v1211PrevJild"></div><div><label>Page From</label><input id="v1211PrevFrom"></div><div><label>Page To</label><input id="v1211PrevTo"></div><div><label>Bahi No.</label><input id="v1211PrevBahi"></div><div><label>Office</label><input id="v1211PrevOffice"></div></div>`));
  const land=$('khataNo')?.closest('.form-card');if(land&&!$('v1211PlotRecords')){const oldGrid=land.querySelector('.land-record-grid');oldGrid?.insertAdjacentHTML('afterend',`<section id="v1211PlotRecords" class="v1211-toggle-card v1211-plot-only"><div class="v1211-toggle-head"><span>Land Records — Khata / Khasra</span></div><div class="v1211-toggle-body"><table class="v1211-record-table"><thead><tr><th>Khata No.</th><th>Khasra No.</th><th>Total Property Area</th><th>में से Sale Area</th><th></th></tr></thead><tbody id="v1211PlotRecordRows"></tbody></table><button type="button" class="btn outline compact v1211-add-row" onclick="v1211AddPlotRecord()">+ Add Khata / Khasra</button><div class="v1211-clear"></div></div></section>`);window.v1211AddPlotRecord?.()}
  const cov=$('v19ResidentialCoveredPanel');if(cov&&!$('v1211CoveredToggle')){const content=cov.innerHTML;cov.innerHTML=`<label class="v1211-toggle-head"><input id="v1211CoveredToggle" type="checkbox" onchange="v1211CoveredChanged()"><span>Covered Area / Plot Construction</span><small>Click to open</small></label><div id="v1211CoveredBody" class="v1211-toggle-body" hidden>${content}</div>`}
}
function card(id,title,inside){return `<section id="${id}" class="v1211-toggle-card v1211-plot-only"><label class="v1211-toggle-head"><input id="${id}Toggle" type="checkbox" onchange="v1211Toggle('${id}')"><span>${title}</span><small>Click to open</small></label><div id="${id}Body" class="v1211-toggle-body" hidden>${inside}</div></section>`}
window.v1211Toggle=id=>{const b=$(id+'Body');if(b)b.hidden=!$(id+'Toggle')?.checked};
window.v1211CoveredChanged=()=>{const on=!!$('v1211CoveredToggle')?.checked,b=$('v1211CoveredBody'),s=$('v19ResCoveredStatus');if(b)b.hidden=!on;if(s){s.value=on?'yes':'no';s.dispatchEvent(new Event('change',{bubbles:true}))}};
window.v1211AddPlotRecord=(d={})=>{const b=$('v1211PlotRecordRows');if(!b)return;const tr=document.createElement('tr');tr.innerHTML=`<td><input data-f="khata" value="${html(d.khata)}" oninput="v1211RecordsChanged()"></td><td><input data-f="khasra" value="${html(d.khasra)}" oninput="v1211RecordsChanged()"></td><td><input data-f="total" type="number" min="0" step="0.0001" value="${html(d.total)}"></td><td><input data-f="sale" type="number" min="0" step="0.0001" value="${html(d.sale)}"></td><td><button type="button" class="btn outline compact" onclick="this.closest('tr').remove();v1211RecordsChanged()">×</button></td>`;b.appendChild(tr)};
function recordRows(){return [...document.querySelectorAll('#v1211PlotRecordRows tr')].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-f]')].map(e=>[e.dataset.f,e.value]))).filter(x=>x.khata||x.khasra)}
window.v1211RecordsChanged=()=>{const a=recordRows(),first=a[0]||{};if($('khataNo'))$('khataNo').value=first.khata||'';if($('khasraNo'))$('khasraNo').value=first.khasra||'';try{syncDraftPreview()}catch(e){}};
function refreshRoad(){if(!isPlot())return;const distance=$('v123DistanceWrap');if(distance)distance.style.setProperty('display','block','important');ensureUi();const sel=$('v1211PlotRoadSelect'),list=candidates(),cat=category();if(!sel)return;if(!cat)sel.innerHTML='<option value="">SELECT DISTANCE FIRST</option>';else if(cat==='200+')sel.innerHTML='<option value="">>200m — VILLAGE BASE RATE</option>';else if(!list.length)sel.innerHTML='<option value="">NO EXACT ROAD MATCH — ENTER MANUAL RATE</option>';else{if(!list.some(r=>txt(r.id)===selectedRoad))selectedRoad=list.length===1?txt(list[0].id):'';sel.innerHTML=(list.length>1?'<option value="">SELECT EXACT MAIN ROAD</option>':'')+list.map(r=>`<option value="${html(r.id)}">${html(r.route||r.name)} — ₹${rowRate(r,cat).toLocaleString('en-IN')}/m² — p${r.page}/${r.group||'-'}</option>`).join('');sel.value=selectedRoad}const x=effective();syncRoadNarrative(x);const st=$('v1211PlotRoadStatus'),btn=$('v1211PlotRoadSource');if(st){st.textContent=x.rate?`${x.source}: ₹${x.rate.toLocaleString('en-IN')}/m²${x.row?` • PDF p${x.row.page}, row ${x.row.row}, group ${x.row.group||'-'}`:''}`:x.source;st.classList.toggle('warn',!x.rate)}if(btn){btn.disabled=!x.row;btn.dataset.page=x.row?.page||''}calcPlot()}
window.v1211PlotRoadChanged=()=>{selectedRoad=txt($('v1211PlotRoadSelect')?.value);manualRate=false;refreshRoad()};window.v1211PlotManualChanged=()=>{manualRate=num($('v1211PlotManualRate')?.value)>0;calcPlot()};window.v1211OpenPlotRoad=()=>{const p=num($('v1211PlotRoadSource')?.dataset.page);if(p)try{window.v115OpenSourcePage?.(p)}catch(e){window.openCircleRatePdf?.()}};
const baseRecalc=window.recalculate;window.recalculate=function(){const c=baseRecalc.apply(this,arguments);if(!isPlot())return c;const x=effective(),rw=typeof roadWidthInfo==='function'?roadWidthInfo():{factor:num($('roadWidth')?.value)||1,percent:0,label:''},official=num(x.rate),final=official*(num(rw.factor)||1),covered=$('v1211CoveredToggle')?.checked?num($('v19ResCoveredM2')?.value)*14000:0,land=num(c.area?.m2)*final,total=land+covered;Object.assign(c,{baseRate:official,distanceRate:official,finalRate:final,rate:final,road:num(rw.factor)||1,roadPercent:num(rw.percent),roadLabel:txt(rw.label),base:land,baseLandValue:land,landValue:land,coveredValue:covered,plot:total});const hidden=$('circleRate');if(hidden)hidden.value=final?String(final):'';lastPlotCalc={...x,final,land,covered,total,category:category(),roadPremium:num(rw.percent),roadWidth:txt(rw.label),selectedBase:currentBase()};if($('circleRateOut'))$('circleRateOut').textContent=official?`₹${Number(final).toLocaleString('en-IN',{maximumFractionDigits:2})}/m²`:'SELECT EXACT MAIN ROAD';if($('valueOut'))$('valueOut').textContent=inr(total);if($('plotValueDisplay'))$('plotValueDisplay').value=inr(total);const note=$('roadRateNote');if(note)note.innerHTML=official?`Village Base: <strong>₹${currentBase().toLocaleString('en-IN')}/m²</strong> &nbsp; → Main Road Distance Rate: <strong>₹${official.toLocaleString('en-IN')}/m²</strong> &nbsp; + Road Width: <strong>${num(rw.percent)}%</strong> &nbsp; = Final: <strong>₹${Number(final).toLocaleString('en-IN',{maximumFractionDigits:2})}/m²</strong>`:'Main Road Distance और exact Applicable Main Road select करें; app अनुमानित rate नहीं लगाएगा।';return c};
const baseDistance=window.v123DistanceChanged;window.v123DistanceChanged=function(){if(!isPlot())return baseDistance?.apply(this,arguments);selectedRoad='';manualRate=false;refreshRoad();try{recalculateStampDuty();syncDraftPreview()}catch(e){}};
const baseChoose=window.chooseLandRate;window.chooseLandRate=function(){const r=baseChoose?.apply(this,arguments);if(isPlot())refreshRoad();return r};const baseLocation=window.selectCircleLocation;window.selectCircleLocation=function(){const r=baseLocation?.apply(this,arguments);if(isPlot()){selectedRoad='';manualRate=false;refreshRoad()}return r};
const baseDraft=window.draftData;window.draftData=function(){const d=baseDraft.apply(this,arguments);if(!isPlot())return d;const prevOn=!!$('v1211PlotPreviousToggle')?.checked;d.plotPreviousTitle={enabled:prevOn,name:txt($('v1211PrevName')?.value),address:txt($('v1211PrevAddress')?.value),regNo:txt($('v1211PrevRegNo')?.value),date:txt($('v1211PrevDate')?.value),jild:txt($('v1211PrevJild')?.value),pageFrom:txt($('v1211PrevFrom')?.value),pageTo:txt($('v1211PrevTo')?.value),bahi:txt($('v1211PrevBahi')?.value),office:txt($('v1211PrevOffice')?.value)};d.plotLandRecords=recordRows();d.plotCovered={enabled:!!$('v1211CoveredToggle')?.checked,areaM2:num($('v19ResCoveredM2')?.value),rate:14000,value:num($('v19ResCoveredM2')?.value)*14000};d.plotMainRoad=lastPlotCalc?{roadId:lastPlotCalc.row?.id||'',road:cleanRoadName(lastPlotCalc.row),roadLabel:lastPlotCalc.row?.route||lastPlotCalc.row?.name||'',distance:lastPlotCalc.category,rate:lastPlotCalc.rate,finalRate:lastPlotCalc.final,roadWidthPremium:lastPlotCalc.roadPremium,page:lastPlotCalc.row?.page||'',row:lastPlotCalc.row?.row||'',group:lastPlotCalc.row?.group||'',manual:manualRate}:{};if(lastPlotCalc){d.pdfBaseCircleRate=num(lastPlotCalc.rate);d.circleRate=num(lastPlotCalc.final);d.finalCircleRate=num(lastPlotCalc.final);d.roadPremiumPercent=num(lastPlotCalc.roadPremium);d.plotValue=num(lastPlotCalc.total);d.mainRoadDistance=txt($('mainRoadDistance')?.value)}return d};
const baseLoad=window.v14LoadDraftFields;window.v14LoadDraftFields=function(d){const r=baseLoad.apply(this,arguments);if(txt(window.__registryRequestedDraftType||d?.registryType).toLowerCase()!=='residential plot')return r;syncMode();const set=(id,v)=>{if($(id))$(id).value=v??''},p=d.plotPreviousTitle||{};$('v1211PlotPreviousToggle').checked=!!p.enabled;v1211Toggle('v1211PlotPrevious');[['v1211PrevName',p.name],['v1211PrevAddress',p.address],['v1211PrevRegNo',p.regNo],['v1211PrevDate',p.date],['v1211PrevJild',p.jild],['v1211PrevFrom',p.pageFrom],['v1211PrevTo',p.pageTo],['v1211PrevBahi',p.bahi],['v1211PrevOffice',p.office]].forEach(x=>set(...x));$('v1211PlotRecordRows').innerHTML='';(d.plotLandRecords?.length?d.plotLandRecords:[{khata:d.khataNo,khasra:d.khasraNo}]).forEach(v1211AddPlotRecord);$('v1211CoveredToggle').checked=!!d.plotCovered?.enabled;set('v19ResCoveredM2',d.plotCovered?.areaM2);v1211CoveredChanged();selectedRoad=txt(d.plotMainRoad?.roadId);manualRate=!!d.plotMainRoad?.manual;set('v1211PlotManualRate',manualRate?d.plotMainRoad?.rate:'');refreshRoad();return r};
if(typeof window.v18CollectWarnings==='function'){const baseWarnings=window.v18CollectWarnings;window.v18CollectWarnings=function(d){const out=baseWarnings.apply(this,arguments),data=d||window.draftData();if(txt(data.registryType).toLowerCase()==='residential plot'){for(const r of (data.plotLandRecords||[])){if(num(r.sale)>num(r.total)&&num(r.total)>0)out.push(`Khasra ${r.khasra||'-'}: sale area total property area से अधिक है।`)}if(!data.plotMainRoad?.distance)out.push('Main Road Distance select नहीं की गई है।');else if(data.plotMainRoad.distance!=='200+'&&!num(data.plotMainRoad?.rate))out.push('Exact Applicable Main Road / official distance rate select नहीं की गई है; अनुमानित rate लागू नहीं होगी।')}return [...new Set(out)]}}
function syncMode(){
  const type=currentDraftType(),on=isPlot(),agri=/agriculture/i.test(type);
  document.body.classList.toggle('v1211-plot-mode',on);
  const heading=$('v1212DraftName');if(heading)heading.textContent=`${type||'Residential Plot'} Registry Draft`;
  const oldPrev=document.querySelector('.previous-title-holder-row');if(oldPrev)oldPrev.style.display=on?'none':(!agri?'':'');
  const oldLand=$('khataNo')?.closest('.land-record-grid');if(oldLand)oldLand.style.display=(on||agri)?'none':'';
  try{ensureUi()}catch(e){console.error('Plot controls initialization',e)}
  if(on){const distance=$('v123DistanceWrap');if(distance)distance.style.display='block';try{refreshRoad()}catch(e){console.error('Plot road initialization',e)}}
}
window.v1211SyncMode=syncMode;
function patchPlotPdf(){if(!isPlot())return;const root=$('legalDraftPreview');if(!root)return;root.querySelectorAll('.v1211-plot-pdf-detail').forEach(e=>e.remove());const d=window.draftData(),page=root.querySelector('.deed-page-4')||root.querySelector('.deed-page:last-child');if(!page)return;const recs=d.plotLandRecords||[],p=d.plotPreviousTitle||{},road=d.plotMainRoad||{};let parts=[];if(recs.length)parts.push(`<p><b>खाता/खसरा एवं क्षेत्रफल विवरण—</b> ${recs.map(r=>`खाता ${html(r.khata||'-')}, खसरा ${html(r.khasra||'-')}, कुल क्षेत्रफल ${html(r.total||'-')} में से विक्रित ${html(r.sale||'-')}`).join('; ')}।</p>`);if(road.road)parts.push(`<p><b>मुख्य सड़क से दूरी / प्रमुख मार्ग विवरण—</b> ${html(road.road)} मुख्य मार्ग से ${html(distanceHindi(road.distance)||road.distance||'-')} की दूरी पर स्थित है। आधिकारिक दूरी-दर ₹${num(road.rate).toLocaleString('en-IN')}/वर्गमीटर; रास्ता-चौड़ाई वृद्धि ${num(road.roadWidthPremium)}%; अंतिम सर्किल दर ₹${num(road.finalRate).toLocaleString('en-IN')}/वर्गमीटर; PDF पृष्ठ ${html(road.page||'-')}, पंक्ति ${html(road.row||'-')}, समूह ${html(road.group||'-')}।</p>`);if(p.enabled)parts.push(`<p><b>पूर्व क्रेता / पूर्व स्वामित्व विवरण—</b> ${html(p.name||'-')}, ${html(p.address||'')}; पंजीकरण संख्या ${html(p.regNo||'-')} दिनांक ${html(p.date||'-')}, जिल्द ${html(p.jild||'-')}, पृष्ठ ${html(p.pageFrom||'-')} से ${html(p.pageTo||'-')}, बही ${html(p.bahi||'-')}, कार्यालय ${html(p.office||'-')}।</p>`);if(parts.length)page.insertAdjacentHTML('beforeend',`<section class="v1211-plot-pdf-detail">${parts.join('')}</section>`)}
const basePreview=window.syncDraftPreview;window.syncDraftPreview=function(){const r=basePreview.apply(this,arguments);try{patchPlotPdf()}catch(e){console.warn('Residential Plot PDF',e)}return r};
window.mutationHtml=function(d){
  const sellers=typeof compactPartiesHtml==='function'?compactPartiesHtml(d.sellers,d.seller,'विक्रेता'):html(d.seller?.name||'-'),buyers=typeof compactPartiesHtml==='function'?compactPartiesHtml(d.buyers,d.buyer,'क्रेता'):html(d.buyer?.name||'-');
  const recs=(d.plotLandRecords||[]).length?d.plotLandRecords:[{khata:d.khataNo,khasra:d.khasraNo,total:'',sale:d.areaM2||''}];
  const finalDate=d.savedAtISO?String(d.savedAtISO).slice(0,10):(typeof v14DateOnly==='function'?v14DateOnly(d):'');
  const recHtml=recs.map((r,i)=>`<tr><td>${i+1}</td><td>${html(r.khata||'-')}</td><td>${html(r.khasra||'-')}</td><td>${html(r.total||'-')}</td><td>${html(r.sale||'-')}</td></tr>`).join('');
  const road=d.plotMainRoad||{},roadLine=road.road?`<p><b>मुख्य मार्ग विवरण:</b> ${html(road.road)}, दूरी ${html(distanceHindi(road.distance)||road.distance||'-')}, आधिकारिक दर ₹${num(road.rate).toLocaleString('en-IN')}/वर्गमीटर (PDF पृष्ठ ${html(road.page||'-')}, पंक्ति ${html(road.row||'-')})।</p>`:'';
  return `<div class="mutation-doc v1211-mutation"><h1>नामान्तरण / दाखिल-खारिज प्रार्थना-पत्र</h1><div class="mutation-meta"><b>रजिस्ट्री संख्या:</b> ${html(d.registryNo||'-')} &nbsp; <b>रजिस्ट्री की तारीख:</b> ${html(finalDate||'-')} &nbsp; <b>तहसील:</b> ${html(d.jurisdiction?.tehsil||'-')}</div><p><b>विक्रेता/अन्तरणकर्ता:</b> ${sellers}</p><p><b>क्रेता/अन्तरिती:</b> ${buyers}</p><p><b>सम्पत्ति का स्थान:</b> ग्राम ${html(d.village||'-')}, तहसील ${html(d.jurisdiction?.tehsil||'-')}, जिला ${html(d.jurisdiction?.district||'Haridwar')}।</p><table class="v1211-mutation-table"><thead><tr><th>क्र.</th><th>खाता</th><th>खसरा</th><th>कुल क्षेत्रफल</th><th>में से विक्रित क्षेत्रफल</th></tr></thead><tbody>${recHtml}</tbody></table>${roadLine}<p><b>विक्रय/प्रतिफल राशि:</b> ${typeof inr==='function'?inr(d.transactionAmount||0):html(d.transactionAmount||0)}</p><div class="v1211-mutation-blanks"><p><b>प्रथम सुनवाई/पेश करने की तारीख:</b> ____________________</p><p><b>नामान्तरण वाद/आवेदन संख्या:</b> ____________________</p></div><div class="v1211-mutation-sign"><span>आवेदक/क्रेता के हस्ताक्षर</span><span>लेखपत्र लेखक/अधिवक्ता</span></div></div>`;
};
const baseSelect=window.selectPropertyType;window.selectPropertyType=function(){const r=baseSelect.apply(this,arguments);syncMode();return r};const baseStart=window.startDraftSteps;window.startDraftSteps=function(){const r=baseStart.apply(this,arguments);syncMode();return r};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',syncMode,{once:true});else syncMode();
})();

(function(){
'use strict';
window.RegistryProModules=window.RegistryProModules||{};
const module=window.RegistryProModules.residentialPlot=window.RegistryProModules.residentialPlot||{};
module.enrichDraft=function(draft){draft.registryType='Residential Plot';return draft;};
})();
